package com.singtel.assignment.utils;

public enum AnimalTypeEnum {
    BIRD,CHICKEN, DUCK, PARROT, ROOSTER, PARROT_NEAR_DOG,PARROT_NEAR_CAT,PARROT_NEAR_DUCK,PARROT_NEAR_ROOSTER,FISH,SHARK,CLOWN_FISH,DOLPHIN,BUTTERFLY,PARROT_NEAR_PHONE;
}
